export const userRubricInitData = {
  rubrics: {
    rubric_1: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_2: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_3: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_4: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_5: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_6: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_7: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_8: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_9: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_10: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_11: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_12: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_13: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_14: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_15: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_16: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_17: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_18: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_19: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    rubric_20: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
  },
};
