export const userCategoryInitData = {
  categories: {
    category_1: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      isAllQuestionsSwiped: false,
      isBlocked: false,
      isCategoryDetailsVisible: true,
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    category_2: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      isAllQuestionsSwiped: false,
      isBlocked: true,
      isCategoryDetailsVisible: true,
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    category_3: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      isAllQuestionsSwiped: false,
      isBlocked: true,
      isCategoryDetailsVisible: true,
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    category_4: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      isAllQuestionsSwiped: false,
      isBlocked: true,
      isCategoryDetailsVisible: true,
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    category_5: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      isAllQuestionsSwiped: false,
      isBlocked: true,
      isCategoryDetailsVisible: true,
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
    category_6: {
      breakPointForCheckingDate: 30,
      currentQuestion: '',
      isAllQuestionsSwiped: false,
      isBlocked: true,
      isCategoryDetailsVisible: true,
      questionSwipeStartDate: '',
      swipedQuestionsPercentage: 0,
    },
  },
};
