export const specialChallengesList = [
  {
    title: {
      en: 'Self Reflection Record',
      pt: 'Registro de autorreflexão',
      de: 'Das Selbstreflexionsprotokoll',
    },
    description: {
      en: 'Implement a new healthy routine in your life. Everytime when you notice strong negative emotions, thoughts, physical sensations or reactions in the context of your relationship, write briefly about them.',
      pt: 'É hora de uma nova rotina em suas vidas. No futuro, por favor, escreva diretamente se tiver algum sentimento, pensamento, sensação física ou reação negativos fortes relacionados ao seu relacionamento.',
      de: 'Zeit für eine neues Tool. Solltet ihr in Zukunft starke negative Gefühle, Gedanken, körperliche Empfindungen oder Reaktionen im Zusammenhang mit deiner Beziehung verspüren, schreibt sie direkt auf. Als eine Art Gedanken - Protokoll.',
    },
    rubrics: ['personal_growth'],
    id: 'special_challenge_1',
    isChallengeSpecial: true,
    specialChallengeType: 'selfReflection',
    challengeCardsData: [
      {
        type: 'data_1',
        categoryBlock: 'Text',
        title: {
          en: 'Info:',
          de: 'Info:',
          pt: 'Info:',
        },
        description1: {
          en: 'A Thought Record is a fundamental tool used in Cognitive Behavioral Therapy (CBT) to help individuals identify and challenge their negative thoughts, which can lead to feelings of anxiety, depression, and other emotional difficulties.',
          de: '"Ein Gedankenprotokoll ist ein fundamentales Instrument, das in der kognitiven Verhaltenstherapie (KVT) eingesetzt wird, um Menschen dabei zu helfen, ihre negativen Gedanken zu erkennen und zu bekämpfen, die zu Angstzuständen, Depressionen und anderen emotionalen Schwierigkeiten führen können.',
          pt: 'Um Registro de Pensamentos é uma ferramenta fundamental usada na Terapia Cognitivo-Comportamental (TCC) para ajudar os indivíduos a identificar e desafiar seus pensamentos negativos, que podem levar a sentimentos de ansiedade, depressão e outras dificuldades emocionais.',
        },
        description2: {
          en: 'When applied to couples, CBT can help address specific issues in a relationship, with the goal of improving communication, increasing understanding, and solving problems. We guide couples in identifying and challenging irrational or harmful thoughts and beliefs, and in developing better coping strategies and communication techniques.',
          de: 'Bei Paaren kann die CBT helfen, bestimmte Probleme in einer Beziehung anzugehen, um die Kommunikation zu verbessern, das Verständnis zu steigern und Probleme zu lösen. Wir helfen damit dem Paar, irrationale oder schädliche Gedanken und Überzeugungen zu erkennen und zu hinterfragen sowie bessere Bewältigungsstrategien und Kommunikationstechniken zu entwickeln.',
          pt: 'Quando aplicada a casais, a TCC pode ajudar a abordar questões específicas em um relacionamento, com o objetivo de melhorar a comunicação, aumentar a compreensão e resolver problemas. Orientamos os casais a identificar e desafiar pensamentos e crenças irracionais ou prejudiciais e a desenvolver melhores estratégias de enfrentamento e técnicas de comunicação.',
        },
        description3: {
          en: 'In a nutshell: we will teach to you clean the lens through which you perceive events, allowing you to see them as they truly happened and without the distortions of past experiences and thinking errors.',
          de: 'In Kürze: Wir bringen dir bei, das Erlebte so einzuordnen wie es tatsächlich war und glaub uns, oftmals wird eben nicht so heiß gegessen wie gekocht wird.',
          pt: 'Em resumo: ensinaremos a limpar as lentes pelas quais você percebe os eventos, permitindo que você os veja como eles realmente aconteceram e sem as distorções de experiências passadas e erros de pensamento.',
        },
      },
      {
        type: 'data_2',
        categoryBlock: 'Text',
        title: {
          en: 'Therapeutic Tip:',
          de: 'Therapeutischer Tipp:',
          pt: 'Dica Terapêutica:',
        },
        description1: {
          en: 'Write them in a table under the following categories.',
          de: 'Schreibe deine Gedanken und Gefühle in einer Tabelle unter den folgenden Kategorien auf.',
          pt: 'Escreva-os em uma tabela com as seguintes categorias.',
        },
        description2: {
          en: 'Then reflect on the experience using the reflection questions below.',
          de: 'Nun nimm dir einen Moment und denke nochmals über das Erlebte nach und stelle dir dazu die folgenden Reflexionsfragen.',
          pt: 'Depois, reflita sobre a experiência usando as perguntas de reflexão abaixo.',
        },
        emotional_reflections: {
          situation: {
            en: 'Situation: Describe the situation which brought up the thoughts and emotions.',
            de: 'Situation: Beschreibe die Situation, die die Gedanken und Gefühle hervorgerufen hat.',
            pt: 'Situação: Descreva a situação que provocou os pensamentos e as emoções.',
          },
          thoughts: {
            en: 'Thoughts: What thoughts, judgements, images or beliefs came to mind?',
            de: 'Gedanken: Welche Gedanken, Sichtweisen, Bilder oder Überzeugungen kamen dir in den Sinn?',
            pt: 'Pensamentos: Que pensamentos, julgamentos, imagens ou crenças vieram à sua mente?',
          },
          emotionsAndSensations: {
            en: 'Emotions and sensations: What emotions did you feel? Rate the strength of emotion (0-100). Where in your body did you sense them?',
            de: 'Emotionen und Empfindungen: Welche Gefühle hat das in dir hervorgerufen? Bewerte die Stärke des Gefühls (0-100). Wo in deinem Körper hast du es gespürt?',
            pt: 'Emoções e sensações: Que emoções você sentiu? Classifique a intensidade da emoção (0-100). Em que parte do seu corpo você a sentiu?',
          },
        },
      },
      {
        type: 'data_3',
        categoryBlock: 'Text',
        title: {
          en: 'Reflection Questions:',
          de: 'Reflexionsfragen:',
          pt: 'Perguntas para reflexão:',
        },
        description1: {
          firstPart: {
            en: 'Are your thoughts and judgements always 100% accurate?',
            de: 'Sind deine Gedanken und Interpretationen immer zu 100% korrekt?',
            pt: 'Seus pensamentos e julgamentos são sempre 100% precisos?',
          },
          secondPart: {
            en: 'Identify the thoughts that were going through your mind just before you started feeling the emotion. These are called "automatic thoughts" because they seem to pop up automatically without any effort on your part.',
            de: 'Identifiziere die Gedanken, die dir durch den Kopf gingen, kurz bevor du die starken Emotionen empfandest. Diese nennt man auch  "automatische Gedanken", weil sie scheinbar automatisch auftauchen, ohne dass du etwas dafür tun musst.',
            pt: 'Identifique os pensamentos que estavam passando por sua mente pouco antes de você começar a sentir a emoção. Esses são chamados de pensamentos automáticos" porque parecem surgir automaticamente sem nenhum esforço de sua parte.',
          },
        },
        description2: {
          firstPart: {
            en: 'What evidence challenges your initial strong negative thought?',
            de: 'Welche Indizien stellen Ihren anfänglich starken negativen Gedanken in Frage?',
            pt: 'Que evidências desafiam seu forte pensamento negativo inicial?',
          },
          secondPart: {
            en: "Think about any evidence that supports the automatic thought or belief. This can help you understand why you're thinking this way.",
            de: 'Denken Sie an alle Indizien, die den automatischen Gedanken oder die Überzeugung unterstützen. Das kann Ihnen helfen zu verstehen, warum Sie so denken.',
            pt: 'Pense em qualquer evidência que apoie o pensamento ou a crença automática. Isso pode ajudá-lo a entender por que você está pensando dessa forma.',
          },
          thirdPart: {
            en: 'Now think about any evidence that does not support the automatic thought or belief. This could include past experiences, relevant facts, or aspects of the situation you may be overlooking.',
            de: 'Denken Sie nun an alle Indizien, die den automatischen Gedanken oder die Überzeugung nicht unterstützen. Dazu könnten frühere Erfahrungen, relevante Fakten oder Aspekte der Situation gehören, die Sie vielleicht übersehen.',
            pt: 'Agora pense em qualquer evidência que não apoie o pensamento ou a crença automática. Isso pode incluir experiências passadas, fatos relevantes ou aspectos da situação que você pode estar ignorando.',
          },
        },
      },
      {
        type: 'data_4',
        categoryBlock: 'Text',
        title: {
          en: 'Reflection Questions:',
          de: 'Reflexionsfragen:',
          pt: 'Perguntas para reflexão:',
        },
        description1: {
          firstPart: {
            en: 'What thinking errors are making your thoughts, feelings, sensation, and reactions more intense?',
            de: 'Welche Denkfehler sind in meinen Gedanken, die meine denkenden Gefühle, Empfindungen und Reaktionen verstärken?',
            pt: 'Quais erros de pensamento estão em meus pensamentos, tornando meus sentimentos, sensações e reações mais intensos?',
          },
          secondPart: {
            en: [
              '- mind reading',
              '- predicting the future',
              '- catastrophising',
              '- discounting the positive',
              '- harsh self-criticism ',
              '- jumping to conclusions',
              '- broad labels',
              '- generalisations',
              "- 'what if's'",
              "- ‘should' 'must' 'need' statements",
              '- past negative experiences',
            ],
            de: [
              '- Gedankenlesen',
              '- die Zukunft vorhersagen',
              '- Katastrophisieren',
              '- Abwertung des Positiven',
              '- harte Selbstkritik',
              '- voreilige Schlüsse ziehen',
              '- Pauschalurteile',
              '- Verallgemeinerungen',
              '- "Was wäre wenn',
              '- "Sollte" &  "Muss"-Aussagen',
            ],
            pt: [
              '- leitura da mente',
              '- previsão do futuro',
              '- catastrofização',
              '- descontar o positivo',
              '- autocrítica severa',
              '- tirar conclusões precipitadas',
              '- rótulos amplos',
              '- generalizações',
              '- "e se',
              '- declarações do tipo "deveria", "deve", "precisa"',
            ],
          },
        },
      },
      {
        type: 'data_5',
        categoryBlock: 'Text',
        title: {
          en: 'Reflection Questions:',
          de: 'Reflexionsfragen:',
          pt: 'Perguntas para reflexão:',
        },
        description1: {
          en: 'Reframe: Do you still have the same view of the situation? Come up with a more balanced or rational thought. This does not necessarily mean a purely positive thought, but rather one that is more aligned with reality.',
          de: 'Neu formulieren: Siehst du die Situation immer noch aus demselben Blickwinkel? Überlege dir einen ausgewogeneren oder rationaleren Gedanken. Damit ist nicht unbedingt ein rein positiver Gedanke gemeint, sondern einer, der mehr mit der Realität übereinstimmt.',
          pt: 'Reenquadre: Você ainda tem o mesmo ponto de vista sobre a situação? Você pode ter um pensamento mais equilibrado ou racional. Isso não significa necessariamente um pensamento puramente positivo, mas sim um que esteja mais alinhado com a realidade.',
        },
        description2: {
          en: 'Re-rate the intensity of your emotion after challenging your automatic thoughts with the balanced thought. Often, the intensity of the emotion decreases when the thought becomes more balanced.',
          de: 'Schätze die Intensität deines Gefühls neu ein, nachdem du deine automatischen Gedanken mit dem ausgewogenen Gedanken herausgefordert hast. Oft nimmt die Intensität der Emotion ab, wenn der Gedanke ausgeglichener wird.',
          pt: 'Avalie novamente a intensidade da emoção depois de desafiar os pensamentos automáticos com o pensamento equilibrado. Muitas vezes, a intensidade da emoção diminui quando o pensamento se torna mais equilibrado.',
        },
      },
    ],
  },
  {
    title: {
      en: 'Vocabulary of feeling',
      pt: 'Vocabulário de sentimentos',
      de: 'Wortschatz der Gefühle',
    },
    description: {
      en: "Write a brief note in which you are expressing how you are feeling when your needs are both being met and not being met. Use the provided vocabulary of feelings. If you do so, don't accuse, use I-Messages and preferable talk about past situations.",
      pt: 'Escreva uma breve nota na qual você expresse como se sente quando suas necessidades estão sendo atendidas e não estão sendo atendidas. Use o vocabulário de sentimentos fornecido.',
      de: 'Nehmt euch bitte je einen Zettel und schreibt auf, wie ihr euch fühlt, wenn eure Bedürfnisse erfüllt werden und wie ihr euch fühlt, wenn Sie nicht erfüllt werden. Benutzt die Liste, sie wird euch helfen.',
    },
    rubrics: ['personal_growth'],
    id: 'special_challenge_2',
    isChallengeSpecial: true,
    specialChallengeType: 'vocabularyOfFeel',
    challengeCardsData: [
      {
        type: 'data_1',
        categoryBlock: 'Text',
        title: {
          en: 'Info:',
          de: 'Info:',
          pt: 'Info:',
        },
        description1: {
          en: "Ever had that feeling when you really want to tell your partner what's going on inside your head, but they just don't seem to catch your drift? Hate to break it to you, but it's often because we're not very good at putting our feelings into words.",
          de: 'Kennen Sie das Gefühl, wenn Sie Ihrem Partner unbedingt sagen wollen, was Ihnen durch den Kopf geht, aber sie/er scheint Sie einfach nicht zu verstehen? Es tut mir leid, Ihnen das sagen zu müssen, aber das liegt oft daran, dass wir unsere Gefühle nicht besonders gut in Worte fassen können.',
          pt: 'Você já teve aquela sensação de querer muito dizer ao seu parceiro o que está acontecendo na sua cabeça, mas ele parece não entender o que você quer dizer? Detesto dizer isso, mas muitas vezes isso acontece porque não somos muito bons em expressar nossos sentimentos em palavras.',
        },
        description2: {
          en: 'In the world of Nonviolent Communication (NVC), emotions are the second element of self-expression; getting better at talking about how you feel helps you connect better with others. Opening up and sharing your feelings can help resolve disagreements. And we will help you with that.',
          de: 'In der Welt der Gewaltfreien Kommunikation (GFK) sind Emotionen das zweite Element des Selbstausdrucks; wenn Sie besser über Ihre Gefühle sprechen können, können Sie sich besser mit anderen verbinden. Sich zu öffnen und seine Gefühle mitzuteilen, kann helfen, Meinungsverschiedenheiten zu lösen.',
          pt: 'No mundo da Comunicação Não Violenta (CNV), as emoções são o segundo elemento para a autoexpressão; melhorar a capacidade de falar sobre como você se sente ajuda a se conectar melhor com os outros. Abrir-se e compartilhar seus sentimentos pode ajudar a resolver desentendimentos. E nós o ajudaremos com isso.',
        },
      },
      {
        type: 'data_2',
        categoryBlock: 'Text',
        title: {
          en: 'Therapeutic Guidance:',
          de: 'Tip des Therapeuten',
          pt: 'Orientação terapêutica:',
        },
        description1: {
          en: "NVC differentiates between articulating genuine emotions and phrases that convey thoughts, judgments, and interpretations. To aid in this, here's a list of adjectives to help you articulate your feelings more effectively.",
          de: 'Die NVC unterscheidet zwischen der Artikulation echter Gefühle und Sätzen, die Gedanken, Urteile und Interpretationen ausdrücken. Anbei finden Sie hier eine Liste von Adjektiven, die Ihnen helfen, Ihre Gefühle effektiver zu formulieren.',
          pt: 'A NVC diferencia entre articular emoções genuínas e frases que transmitem pensamentos, julgamentos e interpretações. Para ajudar nisso, aqui está uma lista de adjetivos para ajudá-lo a articular seus sentimentos de forma mais eficaz.',
        },
      },
      {
        type: 'data_3',
        categoryBlock: 'Text',
        title: {
          en: '…when your needs are met:',
          de: '...wenn Ihre Bedürfnisse befriedigt werden',
          pt: '...quando suas necessidades estão sendo atendidas',
        },
        column1: {
          en: [
            'zestful',
            'alive',
            'vibrant',
            'valued',
            'helpful',
            'reassured',
            'touched',
            'surprised',
            'supported',
            'mellow',
            'quiet',
            'serene',
            'sensitive',
            'breathless',
            'safe',
            'gratified',
            'satisfied',
            'invigorated',
          ],
          de: [
            'lebensfroh',
            'lebendig',
            'lebhaft',
            'wertgeschätzt',
            'hilfreich',
            'beruhigt',
            'gerührt',
            'überrascht',
            'unterstützt',
            'sanftmütig',
            'still',
            'gelassen',
            'empfindlich',
            'atemlos',
            'sicher',
            'erfreut',
            'zufrieden',
            'gestärkt',
          ],
          pt: [
            'zestful',
            'vivo',
            'vibrante',
            'valorizado',
            'útil',
            'tranquilizado',
            'tocado',
            'surpreso',
            'suportado',
            'suave',
            'silencioso',
            'sereno',
            'sensível',
            'sem fôlego',
            'seguro',
            'gratificado',
            'satisfeito',
            'revigorado',
          ],
        },
        column2: {
          en: [
            'esteemed',
            'respected',
            'refreshed',
            'relaxed',
            'rejuvenated',
            'recognized',
            'radiant',
            'warm',
            'protected',
            'peaceful',
            'upbeat',
            'proud',
            'nurtured',
            'moved',
            'wonderful',
            'free',
            'cool',
            'intrigued',
          ],
          de: [
            'geachtet',
            'respektiert',
            'erfrischt',
            'entspannt',
            'verjüngt',
            'anerkannt',
            'strahlend',
            'warm',
            'geschützt',
            'friedlich',
            'optimistisch',
            'stolz',
            'gehegt und gepflegt',
            'bewegt',
            'wunderbar',
            'frei',
            'cool',
            'fasziniert',
          ],
          pt: [
            'respeito',
            'respeitado',
            'renovado',
            'relaxado',
            'rejuvenescido',
            'reconhecido',
            'radiante',
            'quente',
            'protegida',
            'pacífica',
            'otimista',
            'orgulhoso',
            'nutrido',
            'movido',
            'maravilhoso',
            'livre',
            'legal',
            'intrigado',
          ],
        },
      },
      {
        type: 'data_4',
        categoryBlock: 'Text',
        title: {
          en: '…when your needs are met:',
          de: '...wenn Ihre Bedürfnisse befriedigt werden',
          pt: '...quando suas necessidades estão sendo atendidas',
        },
        column1: {
          en: [
            'interested',
            'inspired',
            'encouraged',
            'important',
            'honored',
            'harmonious',
            'thankful',
            'glorious',
            'buoyant',
            'faithful',
            'glad',
            'happy',
            'fascinated',
            'exuberant',
            'ecstatic',
            'expectant',
            'expansive',
            'aroused',
          ],
          de: [
            'interessiert',
            'inspiriert',
            'ermutigt',
            'wichtig',
            'geehrt',
            'harmonisch',
            'dankbar',
            'herrlich',
            'schwimmend',
            'treu',
            'froh',
            'glücklich',
            'fasziniert',
            'überschwänglich',
            'ekstatisch',
            'erwartungsvoll',
            'ausgedehnt',
            'erregt',
          ],
          pt: [
            'interessados',
            'inspirado',
            'incentivado',
            'importante',
            'homenageado',
            'harmonioso',
            'grato',
            'glorioso',
            'flutuante',
            'fiel',
            'feliz',
            'contente',
            'fascinado',
            'exuberante',
            'extático',
            'expectante',
            'expansivo',
            'excitado',
          ],
        },
        column2: {
          en: [
            'elated',
            'stimulated',
            'splendid',
            'spirited',
            'hopeful',
            'amazed',
            'involved',
            'enthusiastic',
            'exhilarated',
            'thrilled',
            'enriched',
            'energized',
            'spellbound',
            'uplifted',
            'effervescent',
            'amused',
            'worthy',
            'carefree',
          ],
          de: [
            'überglücklich',
            'angeregt',
            'prächtig',
            'temperamentvoll',
            'hoffnungsvoll',
            'erstaunt',
            'beteiligt',
            'begeistert',
            'beschwingt',
            'bezaubert',
            'angereichert',
            'energetisiert',
            'verzaubert',
            'erhebend',
            'sprudelnd',
            'amüsiert',
            'würdig',
            'sorglos',
          ],
          pt: [
            'exaltado',
            'estimulado',
            'esplêndido',
            'espirituoso',
            'esperançoso',
            'espantado',
            'envolvidos',
            'entusiasmado',
            'radiante',
            'empolgado',
            'enriquecido',
            'energizado',
            'encantado',
            'elevado',
            'efervescente',
            'divertido',
            'digno',
            'despreocupado',
          ],
        },
      },
      {
        type: 'data_5',
        categoryBlock: 'Text',
        title: {
          en: '…when your needs are met:',
          de: '...wenn Ihre Bedürfnisse befriedigt werden',
          pt: '...quando suas necessidades estão sendo atendidas',
        },
        column1: {
          en: [
            'dazzled',
            'curious',
            'fulfilled',
            'cared-for',
            'comfortable',
            'confident',
            'trusting',
            'connected',
            'tender',
            'understood',
            'complacent',
            'affectionate',
            'empowered',
            'calm',
            'glowing',
            'good-humored',
            'welcomed',
            'wide-awake',
          ],
          de: [
            'geblendet',
            'neugierig',
            'erfüllt',
            'umsorgt',
            'bequem',
            'selbstsicher',
            'vertrauensvoll',
            'verbunden',
            'zärtlich',
            'verstanden',
            'selbstzufrieden',
            'zart',
            'ermächtigt',
            'ruhig',
            'leuchtende',
            'gutgelaunt',
            'willkommen',
            'hellwach',
          ],
          pt: [
            'deslumbrado',
            'curioso',
            'cumprido',
            'cuidada',
            'confortável',
            'confiante',
            'confiança',
            'conectado',
            'concurso',
            'compreendido',
            'complacente',
            'carinhoso',
            'capacitado',
            'calma',
            'brilhante',
            'bem-humorado',
            'bem recebido',
            'bem acordado',
          ],
        },
        column2: {
          en: [
            'adventurous',
            'assured',
            'rapturous',
            'ardent',
            'appreciative',
            'appreciated',
            'passionate',
            'in-love',
            'eager',
            'animated',
            'excited',
            'enlivened',
            'lively',
            'loving',
            'friendly',
            'loved',
            'relieved',
            'alert',
          ],
          de: [
            'abenteuerlustig',
            'zusichernd',
            'verzückt',
            'leidenschaftlich',
            'anerkennend',
            'geschätzt',
            'glühend',
            'verliebt',
            'eifrig',
            'animiert',
            'aufgeregt',
            'belebt',
            'munter',
            'liebevoll',
            'freundlich',
            'geliebt',
            'erleichtert',
            'wach',
          ],
          pt: [
            'aventureiro',
            'assegurado',
            'arrebatador',
            'ardente',
            'apreciativo',
            'apreciado',
            'apaixonado',
            'apaixonado',
            'ansioso',
            'acesa',
            'animado',
            'vivificado',
            'vivo',
            'amoroso',
            'amigável',
            'amado',
            'aliviado',
            'alerta',
          ],
        },
        column3: {
          en: [
            'joyful',
            'merry',
            'cheerful',
            'mirthful',
            'pleasant',
            'adored',
            'admired',
            'accepted',
            'engrossed',
            'absorbed',
            'open',
            'blessed',
          ],
          de: [
            'freudig',
            'fröhlich',
            'heiter',
            'lustig',
            'angenehm',
            'verehrt',
            'bewundert',
            'akzeptiert',
            'beschlagnehmend',
            'absorbiert',
            'offen',
            'gesegnet',
          ],
          pt: [
            'jovial',
            'alegre',
            'limpo',
            'engraçado',
            'agradável',
            'adorado',
            'admirado',
            'aceito',
            'apreensão',
            'absorvido',
            'aberto',
            'abençoado',
          ],
        },
      },
      {
        type: 'data_6',
        categoryBlock: 'Text',
        title: {
          en: '…when your needs are not being met',
          de: '...wenn Ihre Bedürfnisse nicht befriedigt werden',
          pt: '...quando suas necessidades não estão sendo atendidas',
        },
        column1: {
          en: [
            'sad',
            'jittery',
            'betrayed',
            'horrible',
            'anxious',
            'suppressed',
            'redundant',
            'stifled',
            'undervalued',
            'sleepy',
            'gloomy',
            'mopey',
            'lonely',
            'burdened',
            'overwhelmed',
            'silenced',
            'sensitive',
            'unimportant',
          ],
          de: [
            'traurig',
            'bibbernd',
            'verraten',
            'schrecklich',
            'ängstlich',
            'unterdrückt',
            'überflüssig',
            'erstickt',
            'geringgeschätzt',
            'schläfrig',
            'düster',
            'trübselig',
            'einsam',
            'belastet',
            'überfordert',
            'zum Schweigen gebracht',
            'sensibel',
            'unwichtiges',
          ],
          pt: [
            'triste',
            'trêmulo',
            'traído',
            'terrível',
            'temeroso',
            'suprimido',
            'supérfluo',
            'sufocado',
            'subvalorizado',
            'sonolento',
            'tenebroso',
            'sombrio',
            'solitário',
            'sobrecarregado',
            'sobrecarregado',
            'silenciado',
            'sensível',
            'sem importância',
          ],
        },
        column2: {
          en: [
            'unsupported',
            'sabotaged',
            'ridiculed',
            'withdrawn',
            'thwarted',
            'restrained',
            'resentful',
            'repelled',
            'scorned',
            'rejected',
            'smothered',
            'put-down',
            'degraded',
            'hot',
            'provoked',
            'trapped',
            'worried',
            'troubled',
          ],
          de: [
            'nicht unterstützt',
            'sabotiert',
            'lächerlich gemacht',
            'zurückgezogen',
            'ausgebremst',
            'zurückhaltend',
            'nachtragend',
            'abgestoßen',
            'verschmäht',
            'zurückgewiesen',
            'geglüht',
            'heruntergemacht',
            'zurückgestuft',
            'heiß',
            'provoziert',
            'gefangen',
            'besorgt',
            'beunruhigt',
          ],
          pt: [
            'sem apoio',
            'sabotado',
            'ridicularizado',
            'retraído',
            'retardado',
            'reservado',
            'ressentido',
            'repelido',
            'desdenhado',
            'rejeitado',
            'recozido',
            'rebaixar',
            'rebaixado',
            'quente',
            'provocado',
            'preso',
            'preocupado',
            'inquietamente',
          ],
        },
      },
      {
        type: 'data_7',
        categoryBlock: 'Text',
        title: {
          en: '…when your needs are not being met',
          de: '...wenn Ihre Bedürfnisse nicht befriedigt werden',
          pt: '...quando suas necessidades não estão sendo atendidas',
        },
        column1: {
          en: [
            'lazy',
            'pessimistic',
            'mournful',
            'heavy',
            'disturbed',
            'perplexed',
            'bewildered',
            'forlorn',
            'passive',
            'offended',
            'nervous',
            'overlooked',
            'neglected',
            'unheard',
            'unloved',
            'tepid',
            'rancorous',
            'humdrum',
          ],
          de: [
            'faul',
            'pessimistisch',
            'trauernd',
            'schwer',
            'gestört',
            'perplex',
            'verblüfft',
            'verloren',
            'passiv',
            'beleidigt',
            'nervös',
            'übersehen',
            'vernachlässigt',
            'ungehört',
            'ungeliebt',
            'lauwarm',
            'bissig',
            'eintönig',
          ],
          pt: [
            'preguiçoso',
            'pessimista',
            'pesaroso',
            'pesado',
            'pert urbado',
            'perplexo',
            'espantado',
            'perdido',
            'passivo',
            'ofendido',
            'nervoso',
            'descurado',
            'negligenciado',
            'não ouvido',
            'não amado',
            'morno',
            'mordaz',
            'monótono',
          ],
        },
        column2: {
          en: [
            'woeful',
            'miserable',
            'undermined',
            'minimized',
            'blue',
            'mean',
            'left-out',
            'manipulated',
            'morose',
            'hurt',
            'lethargic',
            'irritated',
            'upset',
            'angry',
            'intimidated',
            'intense',
            'insulted',
            'inadequated',
          ],
          de: [
            'kläglich',
            'miserabel',
            'untergraben',
            'klein gemacht',
            'melancholisch',
            'gemein',
            'ausgegrenzt',
            'manipuliert',
            'mürrisch',
            'verletzt',
            'lethargisch',
            'gereizt',
            'verärgert',
            'wütend',
            'eingeschüchtert',
            'intensiv',
            'beschimpft',
            'unzureichend',
          ],
          pt: [
            'miserável',
            'miserável',
            'minado',
            'menosprezado',
            'melancólico',
            'mau',
            'marginalizado',
            'manipulado',
            'mal-humorado',
            'magoado',
            'letárgico',
            'excitado',
            'irritado',
            'angry',
            'intimidado',
            'intenso',
            'insultado',
            'insuficiente',
          ],
        },
      },
      {
        type: 'data_8',
        categoryBlock: 'Text',
        title: {
          en: '…when your needs are not being met',
          de: '...wenn Ihre Bedürfnisse nicht befriedigt werden',
          pt: '...quando suas necessidades não estão sendo atendidas',
        },
        column1: {
          en: [
            'shaky',
            'insignificant',
            'displeased',
            'restless',
            'fidgety',
            'inhibited',
            'wretched',
            'unhappy',
            'indifferent',
            'listless',
            'unsteady',
            'misunderstood',
            'powerless',
            'imposed-upon',
            'impatient',
            'ignored',
            'disregarded',
            'humiliated',
          ],
          de: [
            'zittrig',
            'unbedeutend',
            'unzufrieden',
            'unruhig',
            'Zappelig',
            'gehemmt',
            'elend',
            'unglücklich',
            'gleichgültig',
            'lustlos',
            'Unbeständig',
            'missverstanden',
            'machtlos',
            'auferlegt',
            'ungeduldig',
            'ignoriert',
            'nicht beachtet',
            'gedemütigt',
          ],
          pt: [
            'instável',
            'insignificante',
            'insatisfeito',
            'inquieto',
            'intranquilo',
            'inibido',
            'infeliz',
            'infeliz',
            'indiferente',
            'apático',
            'inconstante',
            'incompreendido',
            'impotente',
            'impostas',
            'impaciente',
            'ignorado',
            'desconsiderado',
            'humilhado',
          ],
        },
        column2: {
          en: [
            'hostile',
            'hesitant',
            'reluctant',
            'frustrated',
            'cold',
            'cool',
            'furious',
            'constrained',
            'fatigued',
            'exploited',
            'excluded',
            'aroused',
            'exhausted',
            'deflated',
            'distressed',
            'forgotten',
            'ashamed',
            'embarrassed',
          ],
          de: [
            'feindselig',
            'zögerlich',
            'zögernd',
            'Frustriert',
            'kalt',
            'kühl',
            'rasend',
            'gezwungen',
            'ermüdet',
            'ausgebeutet',
            'ausgeschlossen',
            'erregt',
            'erschöpft',
            'ausgelaugt',
            'gestresst',
            'vergessen',
            'beschämt',
            'peinlich',
          ],
          pt: [
            'hostil',
            'hesitante',
            'reluctant',
            'Frustrado',
            'frio',
            'cool',
            'frenético',
            'forçado',
            'fatigado',
            'explorados',
            'excluídos',
            'excitado',
            'exausto',
            'esvaziado',
            'estressado',
            'esquecido',
            'envergonhado',
            'embaraçado',
          ],
        },
      },
      {
        type: 'data_9',
        categoryBlock: 'Text',
        title: {
          en: '…when your needs are not being met',
          de: '...wenn Ihre Bedürfnisse nicht befriedigt werden',
          pt: '...quando suas necessidades não estão sendo atendidas',
        },
        column1: {
          en: [
            'sorrowful',
            'numb',
            'bored',
            'disgusted',
            'cheated',
            'unnerved',
            'cornered',
            'panicky',
            'dominated',
            'detached',
            'devalued',
            'unconcerned',
            'despairing',
            'exasperated',
            'disenchanted',
            'nettled',
            'uneasy',
            'uncomfortable',
          ],
          de: [
            'betrübt',
            'taub',
            'gelangweilt',
            'angewidert',
            'betrogen',
            'entnervt',
            'in die Enge getrieben',
            'panisch',
            'do miniert',
            'distanziert',
            'abgewertet',
            'unbesorgt',
            'verzweifelt',
            'exasperated',
            'entzaubert',
            'verstimmt',
            'unbehaglich',
            'unbequem',
          ],
          pt: [
            'entristecido',
            'entorpecido',
            'entediado',
            'enojado',
            'enganado',
            'enervado',
            'encurralado',
            'em pânico',
            'dominado',
            'distante',
            'desvalorizado',
            'despreocupado',
            'desesperado',
            'exasperated',
            'desencantado',
            'descontente',
            'desconfortável',
            'incômoda',
          ],
        },
        column2: {
          en: [
            'suspicious',
            'disappointed',
            'dismayed',
            'discouraged',
            'spiritless',
            'helpless',
            'defeated',
            'depressed',
            'belittled',
            'brokenhearted',
            'guilty',
            'criticized',
            'confused',
            'doomed',
            'judged',
            'jealous',
            'horrified',
            'shocked',
          ],
          de: [
            'misstrauisch',
            'enttäuscht',
            'bestürzt',
            'entmutigt',
            'mutlos',
            'hilflos',
            'besiegt',
            'deprimiert',
            'herabgesetzt',
            'gebrochenen Herzens',
            'schuldig',
            'kritisiert',
            ',verwirrt',
            'zum Scheitern verurteilt',
            'verurteilt',
            'eifersüchtig',
            'entsetzt',
            'schockiert',
          ],
          pt: [
            'desconfiado',
            'desapontado',
            'perplexo',
            'discouraged',
            'desanimado',
            'desamparado',
            'derrotado',
            'deprimido',
            'depreciado',
            'de coração partido',
            'culpado',
            'criticado',
            'confuso',
            'condenado ao fracasso',
            'condenado',
            'ciumento',
            'chocado',
            'chocado',
          ],
        },
      },
      {
        type: 'data_10',
        categoryBlock: 'Text',
        title: {
          en: '…when your needs are not being met',
          de: '...wenn Ihre Bedürfnisse nicht befriedigt werden',
          pt: '...quando suas necessidades não estão sendo atendidas',
        },
        column1: {
          en: [
            'fearful',
            'skeptical',
            'tired',
            'anguished',
            'terrified',
            'scared',
            'sorry',
            'caged',
            'apathetic',
            'patronized',
            'harried',
            'concerned',
            'threatened',
            'embittered',
            'bitter',
            'estranged',
            'alarmed',
            'keyed-up',
          ],
          de: [
            'voller Angst',
            'skeptisch',
            'müde',
            'gequält',
            'erschrocken',
            'verängstigt',
            'bedauernd',
            'eingesperrt',
            'apathisch',
            'bevormundet',
            'bedrängt',
            'betroffen',
            'bedroht',
            'verbittert',
            'bitter',
            'entfremdet',
            'alarmiert',
            'aufgekratzt',
          ],
          pt: [
            'cheio de medo',
            'cético',
            'cansado',
            'atormentado',
            'aterrorizado',
            'assustado',
            'arrependido',
            'aprisionado',
            'apático',
            'apadrinhado',
            'angustiado',
            'afetado',
            'ameaçados',
            'amargurado',
            'amargo',
            'alienado',
            'alarmado',
            'agitado',
          ],
        },
        column2: {
          en: [
            'agitated',
            'unglued',
            'accused',
            'abused',
            'annoyed',
            'dull',
            'weary',
            'downhearted',
            'abandoned',
            'beat',
            'shaky',
            'hesitant',
            'reluctant',
            'withdrawn',
          ],
          de: [
            'aufgewühlt',
            'auseinander',
            'beschuldigt',
            'missbraucht',
            'genervt',
            'stumpf',
            'abgeschafft',
            'niedergeschlagen',
            'Verlassen',
            'gebeutelt',
            'zittrig',
            'zögerlich',
            'zögernd',
            'zurückgezogen',
          ],
          pt: [
            'agitado',
            'à parte',
            'acusado',
            'abusado',
            'rritado',
            'contundente',
            'abolido',
            'abatido',
            'abandonado',
            'abalado',
            'instável',
            'hesitante',
            'hesitante',
            'retraído',
          ],
        },
      },
    ],
  },
  {
    title: {
      en: 'Walk of Gratitude',
      de: 'Spaziergang der Dankbarkeit',
      pt: 'Caminhada da Gratidão',
    },
    description: {
      en: 'From the list provided, select five appreciations you would like to express toward your partner in your own words, adding an example of when your partner demonstrated each action or displayed the positive qualities you are appreciating.',
      de: 'Wir haben eine Liste für dich zusammengestellt. Wähle 5 Dinge aus der Liste, für die du dich gerne bei deinem Partner/Partnerin bedanken möchtest. Geht gemeinsam auf einen schönen Spaziergang. Nehmt euren Partner/Partnerin dabei an die Hand. Es ist immer schön ein konkretes Beispiel für die gezeigten Qualitäten zu haben. Bringt gerne ein paar Notizen.',
      pt: 'Da lista fornecida, selecione cinco apreciações que gostaria de expressar ao seu parceiro com suas próprias palavras, acrescentando um exemplo de quando seu parceiro demonstrou cada ação ou exibiu as qualidades positivas que você está apreciando.',
    },
    rubrics: ['Friendship'],
    id: 'special_challenge_3',
    isChallengeSpecial: true,
    specialChallengeType: 'walkOfGratitude',
    challengeCardsData: [
      {
        type: 'data_1',
        categoryBlock: 'Text',
        title: {
          en: 'Info:',
          de: 'Info:',
          pt: 'Info:',
        },
        description1: {
          en: 'Appreciation and gratitude are considered as fundamental psychological and emotional needs that contribute to a fulfilling and balanced life. Scientific research supports that gratitude practices enhance our mental well-being, leading to reduced anxiety and depression.',
          de: 'Wertschätzung und Dankbarkeit gelten als grundlegende psychologische und emotionale Bedürfnisse, die zu einem erfüllten und ausgeglichenen Leben beitragen. Wissenschaftliche Untersuchungen belegen, dass Praktiken der Dankbarkeit unser geistiges Wohlbefinden steigern und zu weniger Angst und Depression führen.',
          pt: 'A apreciação e a gratidão são consideradas necessidades psicológicas e emocionais fundamentais que contribuem para uma vida plena e equilibrada. Pesquisas científicas sustentam que as práticas de gratidão melhoram nosso bem-estar mental, levando à redução da ansiedade e da depressão.',
        },
        description2: {
          en: 'Therapists report that they see the effect of this exercise immediately. Couples who at the beginning of a therapy session sat quietly and awkwardly suddenly relax, infusing the atmosphere with a sense of ease & laughter.',
          de: 'Therapeuten berichten, dass sie den Effekt dieser Übung sofort sehen: Paare, die zu Beginn einer Therapiesitzung still und unbeholfen dasaßen, entspannen sich plötzlich und die Atmosphäre wird von einem Gefühl der Leichtigkeit und des Lachens erfüllt.',
          pt: 'Os terapeutas relatam que percebem o efeito desse exercício imediatamente. Casais que, no início de uma sessão de terapia, ficavam sentados em silêncio e desajeitados, de repente relaxam, impregnando a atmosfera com uma sensação de tranquilidade e riso.',
        },
        description3: {
          en: "But with so much going on in our everyday lives, it's not surprising that we often just overlook the wonderful qualities of our partners.",
          de: 'Aber im Trubel des Alltags ist es nicht verwunderlich, dass wir die wunderbaren Eigenschaften unserer Partner oft einfach übersehen.',
          pt: 'Mas com tanta coisa acontecendo em nosso cotidiano, não é de surpreender que muitas vezes ignoremos as qualidades maravilhosas de nossos parceiros.',
        },
      },
      {
        type: 'data_2',
        categoryBlock: 'Text',
        title: {
          en: 'Info:',
          de: 'Info:',
          pt: 'Info:',
        },
        description1: {
          en: 'But dont worry we got you. With the ""Walk of Gratitude"" combines these gratitude practices with a natural mood enhancer - Going for a walk -. As walking activates endorphins that elevate your mood and reduce stress, walking hand in hand & intentionally focus on sharing heartfelt gratitude, ignites pathways in your brains linked to positive emotions, fostering deeper emotional connection and appreciation.',
          de: 'Aber keine Sorge. Mit dem "Walk of Gratitude" werden diese Dankbarkeitsübungen mit dem natürlichen Stimmungsaufheller - dem Spazierengehen - kombiniert. Spazierengehen aktiviert Endorphine, die die Stimmung heben und Stress abbauen. Wenn Sie Hand in Hand spazieren gehen und sich absichtlich darauf konzentrieren, aufrichtige Dankbarkeit zu teilen, werden Bahnen in Ihrem Gehirn aktiviert, die mit positiven Emotionen verbunden werden und eine tiefere emotionale Verbindung und Wertschätzung fördern.',
          pt: 'Mas não se preocupe, nós o ajudamos. Com o """"Walk of Gratitude"""", você combina essas práticas de gratidão com um estimulante natural do humor - a caminhada -. Como a caminhada ativa as endorfinas que elevam o humor e reduzem o estresse, caminhar de mãos dadas e se concentrar intencionalmente em compartilhar gratidão sincera acende caminhos em seu cérebro ligados a emoções positivas, promovendo uma conexão emocional mais profunda e apreciação.',
        },
        description2: {
          en: 'In a nutshell you are co-creating mindfulness that acts as a shield against all negative inlfuences on your relationship.',
          de: 'Kurz gesagt: Sie schaffen gemeinsam eine Achtsamkeit, die wie ein Schutzschild gegen alle negativen Einflüsse auf Ihre Beziehung wirkt.',
          pt: 'Em resumo, você está cocriando a atenção plena que age como um escudo contra todas as influências negativas em seu relacionamento.',
        },
        description3: {
          en: 'So grab your Partner and tell him/her what you are really grateful for.',
          de: 'Schnappen Sie sich also Ihren Partner und sagen Sie ihm/ihr, wofür Sie wirklich dankbar sind.',
          pt: 'Portanto, pegue seu parceiro e diga a ele(a) pelo que você realmente é grato(a).',
        },
      },
      {
        type: 'data_3',
        categoryBlock: 'Text',
        title: {
          en: 'Therapeutic Guidance:',
          de: 'Tip des Therapeuten',
          pt: 'Orientação terapêutica:',
        },
        description1: {
          en: 'Remember, the most beautiful and effective thank you is a sincere one. Personalizing these gratitude expressions to align with your unique relationship will make them all the more meaningful.',
          de: 'Denkt daran: Das schönste und effektivste Dankeschön ist ein Aufrichtiges. Und sie werden umso bedeutungsvoller, wenn sie sich konkret auf eure Beziehung beziehen.',
          pt: 'Lembre-se de que o agradecimento mais bonito e eficaz é o sincero. Personalizar essas expressões de gratidão para que se alinhem com seu relacionamento único as tornará ainda mais significativas.',
        },
        description2: {
          en: 'Expressing gratitude should not be limited to just this challenge but should be integrated as a consistent element in your daily love life.',
          de: 'Aber das Ausdrücken von Dankbarkeit sollte sich nicht nur auf diese Challenge beschränken, sondern es sollte ein fester Bestandteil in eurem Liebesleben werden.',
          pt: 'A expressão de gratidão não deve se limitar apenas a esse desafio, mas deve ser integrada como um elemento consistente em sua vida amorosa diária.',
        },
        description3: {
          en: 'Regularly expressing gratitude reinforces the bond between partners & strengthens connection. It promotes feelings of warmth, safety, and reassurance that your partner values and appreciates you.',
          de: 'Regelmäßiges Ausdrücken von Dankbarkeit stärkt die Bindung zwischen den Partnern und stärkt die Verbindung. Es fördert Gefühle von Wärme, Sicherheit und die Gewissheit, dass Ihr Partner Sie schätzt und wertschätzt.',
          pt: 'A expressão regular de gratidão reforça o vínculo entre os parceiros e fortalece a conexão. Promove sentimentos de calor, segurança e garantia de que sua parceira valoriza e aprecia você.',
        },
        description4: {
          en: 'It can enhance empathy and reduce aggression & conflicts, helping couples to support each other even during difficult times. It Improves communication, increases positivity, encourages reciprocity, and boosts satisfaction.',
          de: 'Sie kann das Einfühlungsvermögen verbessern und Aggressionen und Konflikte abbauen und hilft Paaren, sich auch in schwierigen Zeiten gegenseitig zu unterstützen. Sie verbessert die Kommunikation, erhöht die Positivität, fördert die Gegenseitigkeit und steigert die Zufriedenheit.',
          pt: 'Pode aumentar a empatia e reduzir a agressividade e os conflitos, ajudando os casais a se apoiarem mutuamente mesmo em momentos difíceis. Melhora a comunicação, aumenta a positividade, incentiva a reciprocidade e aumenta a satisfação.',
        },
        description5: {
          en: 'In essence, expressing gratitude is a fundamental part of maintaining a healthy, supportive, and loving relationship.',
          de: 'Dankbarkeit zu zeigen ist also ein wesentlicher Bestandteil einer gesunden, unterstützenden und liebevollen Beziehung.',
          pt: 'Em essência, expressar gratidão é uma parte fundamental da manutenção de um relacionamento saudável, solidário e amoroso.',
        },
      },
    ],
  },
  {
    title: {
      en: 'Self - Reflection - identifying my own needs.',
      de: 'Selbst Reflektion - Meine Bedürfnisse',
      pt: 'Desafio de autorreflexão - minhas próprias necessidades',
    },
    description: {
      en: 'Both of you please write down individually, what you think are your pridominant needs? Use the provided list of "What do I need to feel...-Questions" and each choose your basic needs. What do you think are you communcation those needs clearly? Rate yourself. (1 for lousy to 5 amazing)',
      de: 'Schreibt bitte jeder für sich auf, was eurer Meinung nach Eure wichtigsten Bedürfnisse sind. Verwendet die Liste der "Was brauche ich, um mich...-Fragen" und wählen Sie jeweils Ihre Grundbedürfnisse aus. Wie schätzt du deine Kommunikation bzgl. deiner Bedürfnisse ein, Kommunizierst du klar und deutlich deine Bedürfnisse? Bewerte dich selbst. (1 für lausig bis 5 toll)',
      pt: 'Por favor, escreva o que você acha que são suas necessidades mais importantes. Use a lista de "Perguntas sobre o que eu preciso para..." e selecione suas necessidades básicas em cada caso. Como você avalia sua comunicação em relação às suas necessidades? Você comunica suas necessidades com clareza? Classifique-se. (1 para péssimo a 5 para ótimo)',
    },
    rubrics: ['Friendship'],
    id: 'special_challenge_4',
    isChallengeSpecial: true,
    specialChallengeType: 'selfReflectionMyOwnNeeds',
    challengeCardsData: [
      {
        type: 'data_1',
        categoryBlock: 'Text',
        title: {
          en: 'Info:',
          de: 'Info:',
          pt: 'Info:',
        },
        description1: {
          en: "Welcome to our very first challenge. As we embark on this therapeutic journey together, one of the first crucial steps is to develop an in-depth understanding of your own emotional and psychological needs, as well as those of your partner. We've all experienced situations where we felt disappointed or upset about something, only to let those feelings out on our partner.",
          de: 'Willkommen zu unserer allerersten Herausforderung. Wenn wir uns gemeinsam auf diese therapeutische Reise begeben, besteht einer der ersten entscheidenden Schritte darin, ein tiefes Verständnis für deine eigenen emotionalen und psychologischen Bedürfnisse sowie für die Deines Partners zu entwickeln. Wir alle haben schon Situationen erlebt, in denen wir uns über etwas enttäuscht oder verärgert fühlten und diese Gefühle an unserem Partner ausgelassen haben.',
          pt: 'Bem-vindo ao nosso primeiro desafio. Ao embarcarmos juntos nessa jornada terapêutica, um dos primeiros passos cruciais é desenvolver uma compreensão profunda de suas próprias necessidades emocionais e psicológicas, bem como das necessidades de seu parceiro. Todos nós já passamos por situações em que nos sentimos decepcionados ou irritados com alguma coisa e descarregamos esses sentimentos em nosso parceiro.',
        },
        description2: {
          en: "Often, it's only later that we realize our frustration stemmed from our partner not meeting a need we hadn't even identified ourselves, much less communicated to them. Recognizing what you each need to feel fulfilled, loved, secure, means understanding your basic needs are crucial to set a strong foundation for effective communication and interaction, understanding and mutual growth.",
          de: 'Oft stellen wir erst später fest, dass unsere Frustration darauf zurückzuführen ist, dass unser Partner ein Bedürfnis nicht befriedigt hat, das wir nicht einmal selbst erkannt, geschweige denn ihm mitgeteilt haben. Zu erkennen, was jeder von uns benötigt, um sich erfüllt, geliebt und sicher zu fühlen, bedeutet, dass das Verständnis deiner Grundbedürfnisse entscheidend ist, um eine solide Grundlage für effektive Kommunikation und Interaktion, Verständnis und gegenseitiges Wachstum zu schaffen.',
          pt: 'Muitas vezes, só mais tarde percebemos que nossa frustração se deve ao fato de que nosso parceiro não satisfez uma necessidade que nem nós mesmos reconhecemos, muito menos comunicamos a ele. Reconhecer o que cada um de nós precisa para se sentir realizado, amado e seguro significa que entender suas necessidades básicas é crucial para criar uma base sólida para uma comunicação e interação eficazes, compreensão e crescimento mútuo.',
        },
      },
      {
        type: 'data_2',
        categoryBlock: 'Text',
        title: {
          en: 'Therapeutic Guidance:',
          de: 'Tip des Therapeuten',
          pt: 'Orientação terapêutica:',
        },
        description1: {
          en: 'Ao responder a essas perguntas, esforce-se para ser totalmente honesto consigo mesmo e com a outra pessoa. Reconhecer suas próprias necessidades não é uma forma de egoísmo, mas uma parte importante de um relacionamento equilibrado e saudável. As necessidades podem mudar com o tempo, portanto, você deve repetir esse exercício regularmente.',
          de: 'Wenn Ihr diese Fragen durchgeht, bemüht Euch bitte um absolute Ehrlichkeit, mit euch selbst und dem anderen Gegenüber. Das Erkennen der eigenen Bedürfnisse ist keine Form von Egoismus, sondern ein wichtiger Bestandteil einer ausgewogenen und gesunden Beziehung. Die Bedürfnisse können sich im Laufe der Zeit ändern, daher sollten Sie diese Übung regelmäßig wiederholen.',
          pt: 'Ao responder a essas perguntas, esforce-se para ser totalmente honesto consigo mesmo e com a outra pessoa. Reconhecer suas próprias necessidades não é uma forma de egoísmo, mas uma parte importante de um relacionamento equilibrado e saudável. As necessidades podem mudar com o tempo, portanto, você deve repetir esse exercício regularmente.',
        },
        description2: {
          en: "Step 1: Understanding Yourself: Recognize your feelings, needs, and behaviors. It's about noticing patterns, including those that might be detrimental to your relationship. This self-awareness lays the groundwork for empathy towards your partner.",
          de: 'Schritt 1: Sich selbst kennenlernen und besser verstehen. Erkenne deine Gefühle, Bedürfnisse und Verhaltensweisen. Es geht darum, Muster zu erkennen, auch solche, die deiner Beziehung schaden könnten. Diese Selbsterkenntnis legt den Grundstein für das Einfühlungsvermögen gegenüber Ihrem Partner.',
          pt: 'Etapa 1: Conheça a si mesmo e compreenda-se melhor. Reconheça seus sentimentos, necessidades e comportamentos. Trata-se de reconhecer padrões, inclusive aqueles que podem prejudicar seu relacionamento. Esse autoconhecimento estabelece a base para a empatia com seu parceiro.',
        },
        description3: {
          en: 'Step 2: Exploring Personal History and Emotional Triggers: Discover the roots of your emotional responses. This involves identifying what sets off certain emotions in you and understanding your unique communication style.',
          de: 'Schritt 2: Erforschung der persönlichen Geschichte und der emotionalen Auslöser: Entdeckt die Wurzeln deiner emotionalen Reaktionen. Dazu gehört es, herauszufinden, was bestimmte Emotionen in dir auslöst, und deinen einzigartigen Kommunikationsstil zu verstehen.',
          pt: 'Etapa 2: Explorar sua história pessoal e os gatilhos emocionais: Descubra as raízes de suas reações emocionais. Isso inclui descobrir o que desencadeia certas emoções em você e entender seu estilo de comunicação exclusivo.',
        },
      },
      {
        type: 'data_3',
        categoryBlock: 'Text',
        title: {
          en: 'Therapeutic Guidance:',
          de: 'Tip des Therapeuten',
          pt: 'Orientação terapêutica:',
        },

        description1: {
          en: "Step 3: Effective Communication and Behavior Modification: By being aware of your emotional landscape, you're better positioned to express your feelings and needs. Understanding where your reactions stem from allows you to make necessary adjustments to your behavior, fostering a healthier relationship.",
          de: 'Schritt 3: Effektive Kommunikation und Verhaltensmodifikation: Wenn du dir deiner Gefühlswelt bewusst bist, dann bist du besser in der Lage, deine Gefühle und Bedürfnisse auszudrücken. Wenn du verstehst, woher Deine Reaktionen kommen, kannst du dein Verhalten entsprechend anpassen und so eine gesündere Beziehung fördern.',
          pt: 'Etapa 3: Comunicação eficaz e modificação de comportamento: Quando você está ciente do seu mundo emocional, é mais capaz de expressar seus sentimentos e necessidades. Quando entender de onde vêm suas reações, poderá ajustar seu comportamento de acordo com elas e promover um relacionamento mais saudável.',
        },
        description2: {
          en: 'Remember, the journey of self-reflection is about introspection, understanding, and growth, both as an individual and as a partner in a relationship.',
          de: 'Denk daran, dass es bei der Reise der Selbstreflexion um Selbstbeobachtung, Verständnis und Wachstum geht, sowohl als Einzelperson als auch als Partner in einer Beziehung.',
          pt: 'Lembre-se de que a jornada da autorreflexão tem a ver com introspecção, compreensão e crescimento, tanto como indivíduo quanto como parceiro em um relacionamento.',
        },
      },
      {
        type: 'data_4',
        categoryBlock: 'Text',
        title: {
          en: 'Questions:',
          de: 'Fragen:',
          pt: 'Perguntas:',
        },

        description1: {
          en: 'What do I need to feel most loved and cherished in this relationship?',
          de: 'Was brauche ich, um mich in dieser Beziehung am meisten geliebt und wertgeschätzt zu fühlen?',
          pt: 'O que eu preciso para me sentir mais amado e querido nesse relacionamento?',
        },
        description2: {
          en: 'What do I need to feel emotionally close rather than distant from my partner?',
          de: 'Was brauche ich, um mich meinem Partner emotional nah und nicht distanziert zu fühlen?',
          pt: 'Do que preciso para me sentir emocionalmente próximo em vez de distante de meu parceiro?',
        },
        description3: {
          en: 'What do I need to feel secure in our relationship?',
          de: 'Was brauche ich, um mich in unserer Beziehung sicher zu fühlen?',
          pt: 'Do que preciso para me sentir seguro em nosso relacionamento?',
        },
        description4: {
          en: 'What do I need to feel emotionally safe with my partner?',
          de: 'Was brauche ich, um mich bei meinem Partner emotional sicher zu fühlen?',
          pt: 'Do que preciso para me sentir emocionalmente seguro com meu parceiro?',
        },
        description5: {
          en: 'What do I need to feel truly understood by my partner?',
          de: 'Was brauche ich, um mich von meinem Partner wirklich verstanden zu fühlen?',
          pt: 'Do que preciso para me sentir verdadeiramente compreendido por meu parceiro?',
        },
        description6: {
          en: 'What do I need regarding personal space and alone time in this relationship?',
          de: 'Was brauche ich an persönlichem Freiraum und Zeit für mich allein in dieser Beziehung?',
          pt: 'O que eu preciso com relação ao espaço pessoal e ao tempo sozinho nesse relacionamento?',
        },
        description7: {
          en: 'What do I need to hear or see to feel verbally affirmed by my partner?',
          de: 'Was muss ich hören oder sehen, um mich von meinem Partner verbal bestätigt zu fühlen?',
          pt: 'O que preciso ouvir ou ver para me sentir verbalmente afirmado por meu parceiro?',
        },
        description8: {
          en: 'What do I need to feel supported by my partner?',
          de: 'Was brauche ich, um mich von meinem Partner unterstützt zu fühlen?',
          pt: 'Do que preciso para me sentir apoiado por meu parceiro?',
        },
        description9: {
          en: 'What do I need when handling stress or crises as a couple?',
          de: 'Was brauche ich, um Stress oder Krisen als Paar zu bewältigen?',
          pt: 'Do que preciso para lidar com estresse ou crises como casal?',
        },
        description10: {
          en: 'What do I need to feel loved in my primary ""love languages"" (e.g., physical touch, words of affirmation, quality time, etc.)?',
          de: 'Was brauche ich, um mich in meinen primären """"Liebessprachen"""" geliebt zu fühlen (z. B. körperliche Berührungen, Worte der Bestätigung, wertvolle Zeit usw.)?',
          pt: 'Do que preciso para me sentir amado em minhas principais """" linguagens amorosas"""" (por exemplo, toque físico, palavras de afirmação, tempo de qualidade, etc.)?',
        },
      },
      {
        type: 'data_5',
        categoryBlock: 'Text',
        title: {
          en: 'Questions:',
          de: 'Fragen:',
          pt: 'Perguntas:',
        },

        description1: {
          en: 'What do I need to avoid feeling disrespected or undervalued in this relationship?',
          de: 'Was brauche ich, um zu vermeiden, dass ich mich in dieser Beziehung nicht respektiert oder unterbewertet fühle?',
          pt: 'Do que preciso para não me sentir desrespeitado ou desvalorizado nesse relacionamento?',
        },
        description2: {
          en: 'What do I need to resolve conflicts effectively with my partner?',
          de: 'Was brauche ich, um Konflikte mit meinem Partner effektiv zu lösen?',
          pt: 'Do que preciso para resolver conflitos de forma eficaz com meu parceiro?',
        },
        description3: {
          en: 'What do I need regarding family involvement and boundaries?',
          de: 'Was brauche ich in Bezug auf die Einbeziehung der Familie und Grenzen?',
          pt: 'O que eu preciso com relação ao envolvimento familiar e aos limites?',
        },
        description4: {
          en: 'What do I need to feel genuinely committed to and by my partner?',
          de: 'Was brauche ich, um mich meinem Partner gegenüber wirklich verpflichtet zu fühlen?',
          pt: 'Do que preciso para me sentir genuinamente comprometido com meu parceiro e por ele?',
        },
        description5: {
          en: 'What do I need to feel financially stable and secure in this relationship?',
          de: 'Was brauche ich, um mich in dieser Beziehung finanziell stabil und sicher zu fühlen?',
          pt: 'O que eu preciso para me sentir financeiramente estável e seguro nesse relacionamento?',
        },
        description6: {
          en: 'What do I need regarding physical intimacy for my emotional well-being?',
          de: 'Was brauche ich an körperlicher Intimität für mein emotionales Wohlbefinden?',
          pt: 'O que eu preciso em relação à intimidade física para meu bem-estar emocional?',
        },
        description7: {
          en: 'What do I need to feel comfortable with public displays of affection?',
          de: 'Was brauche ich, um mich bei der Zurschaustellung von Zuneigung in der Öffentlichkeit wohl zu fühlen?',
          pt: 'O que eu preciso para me sentir confortável com demonstrações públicas de afeto?',
        },
        description8: {
          en: 'What do I need for future planning and stability in terms of housing, family, and career?',
          de: 'Was brauche ich für meine Zukunftsplanung und Stabilität in Bezug auf Wohnung, Familie und Beruf?',
          pt: 'Do que preciso para planejar o futuro e ter estabilidade em termos de moradia, família e carreira?',
        },
        description9: {
          en: 'What do I need to share in terms of activities or hobbies with my partner, and what do I prefer to do alone or with others?',
          de: 'Was muss ich an Aktivitäten oder Hobbys mit meinem Partner teilen, und was mache ich lieber allein oder mit anderen?',
          pt: 'O que preciso compartilhar em termos de atividades ou hobbies com meu parceiro e o que prefiro fazer sozinho ou com outras pessoas?',
        },
        description10: {
          en: 'What do I need to grow or change as a person, and how can my partner support that journey?',
          de: 'Was brauche ich, um mich als Person zu entwickeln oder zu verändern, und wie kann mein Partner mich auf diesem Weg unterstützen?',
          pt: 'O que eu preciso para crescer ou mudar como pessoa, e como meu parceiro pode apoiar essa jornada?',
        },
      },
    ],
  },
];
